### ISSUE TITLE
Prework assigment

### ISSUE THREAD

**Issue by epishan** [epish/coderschool-blog-app#1]
Hello out there! 
That's my pre-work assiment, happy to announce. Hope, it's not too late :)

cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Rails submission, epish!

 :star: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by nvh0412** [comment]
HI @epish 

We're doing the final round of review of submission, it seem like your submission is incomplete. Would you like to update your assignment with more changes before we make the final decision?

**Comment by epishan** [comment]
Hi @nvh0412, I don't have any extra feature to submit, but can work on it if there is some time. So is there the due date for the final submission? 

If it counts I also put a Docker file with Rails+PostgreSQL setup into the repo

Thank you!

**Comment by nvh0412** [comment]
Hi @epish ,

Nice to see some excited technologies which you want to apply into this prework, but you should know that if you want to CoderSchoool accept your prework, you have to complete all **required functionality**. Currently, you haven't completed those features yet. If you really want to join Ruby Course of CodeSchool, please try to complete them.

If you don't have time for this, you can register next Ruby Course :smile: . It will be opened soon.

/cc @harley. @coderschoolreview

**Comment by epishan** [comment]
I see, okay, challenge accepted :smile:  will try to finish all the required features. Thanks for the update @nvh0412

**Comment by epishan** [comment]
Hi @nvh0412, I resubmitted  the prework with the all required features completed. Please find time to review, hope it's not too late!

Thanks,
Serge
